### PR TITLE
Add registration start event

### PR DESCRIPTION
**Pull request by verygreenboi**
Notify user when the registration process starts

### CODE REVIEW

**Comment by DavidTheProgrammer** [comment]
I think I accidentally duplicated your work. https://github.com/AnthonyNahas/ngx-auth-firebaseui/pull/584

Your PR has been open since August, this isn't encouraging. Is this project active?

**Comment by vbourdeix** [comment]
@DavidTheProgrammer You're right, it seems the creator of this project don't have time anymore, so now I have to use my own fork in order to fix the bugs myself, depending on my specific needs. Though I haven't been able to compile the project recently so I cannot use my fork, which sucks :-/

**Comment by AnthonyNahas** [comment]
Hello guys

I am not able to update this library for the moment... I have more than 15 OS projects to maintain....

Does anyone interested to be an active maintainer to this library??

**Comment by DavidTheProgrammer** [comment]
@AnthonyNahas I'd be happy to but I've never maintained an OS Project before. Idk how much it takes, but I'd be happy to have a look at the issues and PRs

**Comment by AnthonyNahas** [comment]
I will close this PR since #584 has been merged already.

Please consider reopening this PR if you are still facing some troubles


thank you all 


cheers🍻

**Pull request closed without merging**
