### PR TITLE
Feature/fix null checks in aot compile

### LINKED ISSUE #376: AOT Build Fails when using strictNullChecks
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
macOS Mojave 10.14.6

### Versions
Angular CLI: 8.3.10
Node: 10.15.3
OS: darwin x64
Angular: 8.2.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.10
@angular-devkit/build-angular      0.803.10
@angular-devkit/build-ng-packagr   0.803.10
@angular-devkit/build-optimizer    0.803.10
@angular-devkit/build-webpack      0.803.10
@angular-devkit/core               8.3.10
@angular-devkit/schematics         8.3.10
@angular/cdk                       8.2.3
@angular/cli                       8.3.10
@angular/fire                      5.2.1
@angular/flex-layout               8.0.0-beta.27
@angular/material                  8.2.3
@angular/material-moment-adapter   8.2.3
@ngtools/webpack                   8.3.10
@schematics/angular                8.3.10
@schematics/update                 0.803.10
ng-packagr                         5.7.0
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2

#### Enable strictNullChecks
tsconfig.json
```
"compilerOptions": {
  "strictNullChecks": true,
  ...
}
...
```
#### Build with AOT
```
ng build --aot
```

### The log given by the failure
Screen Shot 2019-10-21 at 12 56 10 pm

### Desired functionality
When building an angular application it appears to be importing, building and packaging the ngx-auth-firebaseui components in AOT mode which is causing the errors.

### Mention any other details that might be useful
Ideally if the package using the `strict` compiler option would be ideal; At the very least having `strictNullChecks`. There's quite a few places where these errors pop up which can result in unexpected behaviour in the form of runtime errors so this should also be looked at.

It would also be worth looking at using `undefined` over `null`; There's quite a bit of discussion around supporting this however I thought it's worth mentioning.

### PR DESCRIPTION
**Pull request by the0rem**
This closes #376 but fixing some of the unhandled null values in the package. There are still a few files which have unhandled null values however the goal of this PR is to address the linked issue so that AOT compile will pass in `strict` mode.

### CODE REVIEW

**Comment by the0rem** [comment]
Hi @AnthonyNahas it would be great if I could get your feedback on this PR. Do you have any feedback prior to merging?

**Comment by the0rem** [comment]
Hi @AnthonyNahas any update on this?

**Comment by AnthonyNahas** [comment]
please give some extra days to check that!

I am planning in parallel to migrate the build system from gulp to native angular ci

this PR would be a start👌

**Comment by AnthonyNahas** [comment]
Thanks for contributing 🍻

**Pull request merged**
