### PR TITLE
WIP: chore(deps): first try for angular 9 migration

### PR DESCRIPTION
**Pull request by jeandat**
Angular 9 was supposed to go out in november. We are in february and there are already 13 release candidates. It will probably goes out soon.

I think it would be good to be compatible with angular 9 as soon it is released notably because this library is popular.

I tried to upgrade dependencies to angular 9 but I'm facing a wall. 
It seems to me the build is not standard and using private api in order to compile angular code (ngc) as mentionned [here](https://github.com/angular/angular/issues/32352).

I don't have the background on this project to understand choices that have been made or even fully understand the current gulp build which seems complex.

I think it should be you Anthony that works on this. Do you think you could tackle this? As the person who made the actual build you might migrate easily.

Right now I had to add another private api in order to make ngc works but then it fails later on (modules are not found). I don't know much about all this and I don't think I will get anywhere. 

Here is a fresh PR that initiates things. Anthony, could you take over please?

### CODE REVIEW

**Comment by jeandat** [comment]
@AnthonyNahas

**Comment by AnthonyNahas** [comment]
@jeandat thanks for trying to support angular v9, but actually I was planning to change the whole build system of the library and stop using rollup and gulp!

Stay up to date! I m gonna release soon a new major version

**Comment by jeandat** [comment]
Oh yeah, music to my ears 👍

**Comment by AnthonyNahas** [comment]
since I have [angular-material-extensions passwors strength](https://github.com/angular-material-extensions/password-strength) as dependency ... I am currently upgrading that library to v9 before continuing the release for ngx-auth-firebaseui 

☢

**Comment by cedvdb** [comment]
any news on the support for v9 ?

**Comment by AnthonyNahas** [comment]
v4 is supporting angular v9


a big thanks for trying to make it compatible earlier than I did

**Pull request closed without merging**
